# Complete Streamlit theme configuration example
# Reference: https://docs.streamlit.io/develop/concepts/configuration/theming

[theme]
# Base theme: "light" or "dark"
base = "light"

# Primary accent color for buttons, focus, etc.
primaryColor = "#FF6B6B"

# Main app background color
backgroundColor = "#FFFFFF"

# Secondary background for widgets, headers, code blocks
secondaryBackgroundColor = "#F0F2F6"

# Default text color
textColor = "#262730"

# Link color
linkColor = "#FF6B6B"

# Underline links (true/false)
linkUnderline = true

# Background for code blocks and inline code
codeBackgroundColor = "#F8F9FA"

# Background for dataframe headers
dataframeHeaderBackgroundColor = "#E9ECEF"

# Base border radius for elements (small=0.25rem, medium=0.5rem, large=0.75rem, full=1rem, none=0rem)
baseRadius = "medium"

# Button border radius (overrides baseRadius)
buttonRadius = "medium"

# Border color for elements
borderColor = "#DEE2E6"

# Dataframe border color
dataframeBorderColor = "#DEE2E6"

# Show borders on unfocused widgets (true/false)
showWidgetBorder = false

# Show border between sidebar and main content (true/false)
showSidebarBorder = true

# Font family
font = "sans serif"

# Basic color palette examples (red, orange, etc.)
# Each can have Color, BackgroundColor, TextColor variants
redColor = "#FF0000"
orangeColor = "#FFA500"
yellowColor = "#FFFF00"
greenColor = "#008000"
blueColor = "#0000FF"
violetColor = "#8A2BE2"
grayColor = "#808080"

# Chart colors (arrays of colors for categorical/sequential)
# chartCategoricalColors = ["#FF6B6B", "#4ECDC4", "#45B7D1"]
# chartSequentialColors = ["#FF6B6B", "#FF8E8E", "#FFB6B6"]

# Sidebar-specific overrides
[theme.sidebar]
# Override primary color in sidebar
primaryColor = "#4ECDC4"

# Sidebar background (swaps with secondary if not set)
backgroundColor = "#F8F9FA"

# Sidebar secondary background
secondaryBackgroundColor = "#E9ECEF"

# Sidebar text color
textColor = "#495057"

# Sidebar base radius
baseRadius = "small"

# Show widget borders in sidebar
showWidgetBorder = true
